// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5BsRoElKfVQHppH1-idAmsKv1qZcbMH4',
    appId: '1:916781057358:web:3ab0c3ad68e361ed6e0a1f',
    messagingSenderId: '916781057358',
    projectId: 'my-app-759ba',
    authDomain: 'my-app-759ba.firebaseapp.com',
    storageBucket: 'my-app-759ba.appspot.com',
    measurementId: 'G-95ET29KPXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbtptaRhF6c3esgs9EMTR4YCeMQDE2aZs',
    appId: '1:916781057358:android:88ebdecd830c12eb6e0a1f',
    messagingSenderId: '916781057358',
    projectId: 'my-app-759ba',
    storageBucket: 'my-app-759ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYgbBntXDNres_9RUf2ZTLL-fg7ggE054',
    appId: '1:916781057358:ios:f6179ef1ef2d95536e0a1f',
    messagingSenderId: '916781057358',
    projectId: 'my-app-759ba',
    storageBucket: 'my-app-759ba.appspot.com',
    iosBundleId: 'com.example.testZd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYgbBntXDNres_9RUf2ZTLL-fg7ggE054',
    appId: '1:916781057358:ios:20879b4126cdac166e0a1f',
    messagingSenderId: '916781057358',
    projectId: 'my-app-759ba',
    storageBucket: 'my-app-759ba.appspot.com',
    iosBundleId: 'com.example.testZd.RunnerTests',
  );
}
