// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd51neL6iiXKDYn7Bq1cGuqgHad7b4AVc',
    appId: '1:669132196339:web:d17b817f55503273e6ea86',
    messagingSenderId: '669132196339',
    projectId: 'sign-in-bed99',
    authDomain: 'sign-in-bed99.firebaseapp.com',
    storageBucket: 'sign-in-bed99.appspot.com',
    measurementId: 'G-JKN606LLF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxyCnQF7cFUGGRjtHY9XRtCk-fFzWlcbk',
    appId: '1:669132196339:android:6857cd2e21b828cfe6ea86',
    messagingSenderId: '669132196339',
    projectId: 'sign-in-bed99',
    storageBucket: 'sign-in-bed99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGdsV3gLsLWSxDqiO8yXyjguwcT4ZG_7w',
    appId: '1:669132196339:ios:8989b3506777a9e7e6ea86',
    messagingSenderId: '669132196339',
    projectId: 'sign-in-bed99',
    storageBucket: 'sign-in-bed99.appspot.com',
    iosClientId: '669132196339-6ktjs0c8hljhcrc3aq7o9gk9pev98mf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.siginIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGdsV3gLsLWSxDqiO8yXyjguwcT4ZG_7w',
    appId: '1:669132196339:ios:8989b3506777a9e7e6ea86',
    messagingSenderId: '669132196339',
    projectId: 'sign-in-bed99',
    storageBucket: 'sign-in-bed99.appspot.com',
    iosClientId: '669132196339-6ktjs0c8hljhcrc3aq7o9gk9pev98mf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.siginIn',
  );
}
